package timetable;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Toolkit;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

import client.subject.Subject;

public class DrawTimeTable extends JPanel{
	JPanel p1_1, p1_2, p1_3, p1_4, p1_5, p1_6;
	JPanel p2_1, p2_2, p2_3, p2_4, p2_5, p2_6;
	JPanel p3_1, p3_2, p3_3, p3_4, p3_5, p3_6;
	JPanel p4_1, p4_2, p4_3, p4_4, p4_5, p4_6;
	JPanel p5_1, p5_2, p5_3, p5_4, p5_5, p5_6;
	JPanel p6_1, p6_2, p6_3, p6_4, p6_5, p6_6;
	JPanel p7_1, p7_2, p7_3, p7_4, p7_5, p7_6;
	JPanel p8_1, p8_2, p8_3, p8_4, p8_5, p8_6;
	JPanel p9_1, p9_2, p9_3, p9_4, p9_5, p9_6;

	public DrawTimeTable() {
		setBorder(BorderFactory.createTitledBorder("½Ã°£Ç¥"));
		setLayout(new GridLayout(9, 6));

		p1_1=new JPanel();	p1_1.setBackground(Color.black);		add(p1_1);
		p1_1.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p1_2=new JPanel();	p1_2.setBackground(Color.black);		add(p1_2);
		p1_2.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb1_2=new JLabel("¿ù");	p1_2.add(lb1_2);
		lb1_2.setForeground(Color.WHITE);
		lb1_2.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb1_2.setHorizontalAlignment(SwingConstants.CENTER);		
		p1_3=new JPanel();	p1_3.setBackground(Color.black);		add(p1_3);
		p1_3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb1_3=new JLabel("È­");	p1_3.add(lb1_3);
		lb1_3.setForeground(Color.WHITE);
		lb1_3.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb1_3.setHorizontalAlignment(SwingConstants.CENTER);	
		p1_4=new JPanel();	p1_4.setBackground(Color.black);		add(p1_4);
		p1_4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb1_4=new JLabel("¼ö");	p1_4.add(lb1_4);
		lb1_4.setForeground(Color.WHITE);
		lb1_4.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb1_4.setHorizontalAlignment(SwingConstants.CENTER);	
		p1_5=new JPanel();	p1_5.setBackground(Color.black);		add(p1_5);
		p1_5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb1_5=new JLabel("¸ñ");	p1_5.add(lb1_5);
		lb1_5.setForeground(Color.WHITE);
		lb1_5.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb1_5.setHorizontalAlignment(SwingConstants.CENTER);	
		p1_6=new JPanel();	p1_6.setBackground(Color.black);		add(p1_6);
		p1_6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb1_6=new JLabel("±Ý");	p1_6.add(lb1_6);
		lb1_6.setForeground(Color.WHITE);
		lb1_6.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb1_6.setHorizontalAlignment(SwingConstants.CENTER);	
		p2_1=new JPanel();	p2_1.setBackground(Color.black);		add(p2_1);
		p2_1.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb2_1=new JLabel("1");	p2_1.add(lb2_1);
		lb2_1.setForeground(Color.WHITE);
		lb2_1.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb2_1.setHorizontalAlignment(SwingConstants.CENTER);	
		p2_2=new JPanel();	p2_2.setBackground(Color.WHITE);		add(p2_2);
		p2_2.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p2_3=new JPanel();	p2_3.setBackground(Color.WHITE);		add(p2_3);
		p2_3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p2_4=new JPanel();	p2_4.setBackground(Color.WHITE);		add(p2_4);
		p2_4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p2_5=new JPanel();	p2_5.setBackground(Color.WHITE);		add(p2_5);
		p2_5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p2_6=new JPanel();	p2_6.setBackground(Color.WHITE);		add(p2_6);
		p2_6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p3_1=new JPanel();	p3_1.setBackground(Color.black);		add(p3_1);
		p3_1.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb3_1=new JLabel("2");	p3_1.add(lb3_1);
		lb3_1.setForeground(Color.WHITE);
		lb3_1.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb3_1.setHorizontalAlignment(SwingConstants.CENTER);
		p3_2=new JPanel();	p3_2.setBackground(Color.WHITE);		add(p3_2);
		p3_2.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p3_3=new JPanel();	p3_3.setBackground(Color.WHITE);		add(p3_3);
		p3_3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p3_4=new JPanel();	p3_4.setBackground(Color.WHITE);		add(p3_4);
		p3_4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p3_5=new JPanel();	p3_5.setBackground(Color.WHITE);		add(p3_5);
		p3_5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p3_6=new JPanel();	p3_6.setBackground(Color.WHITE);		add(p3_6);
		p3_6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p4_1=new JPanel();	p4_1.setBackground(Color.black);		add(p4_1);
		p4_1.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb4_1=new JLabel("3");	p4_1.add(lb4_1);
		lb4_1.setForeground(Color.WHITE);
		lb4_1.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb4_1.setHorizontalAlignment(SwingConstants.CENTER);
		p4_2=new JPanel();	p4_2.setBackground(Color.WHITE);		add(p4_2);
		p4_2.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p4_3=new JPanel();	p4_3.setBackground(Color.WHITE);		add(p4_3);
		p4_3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p4_4=new JPanel();	p4_4.setBackground(Color.WHITE);		add(p4_4);
		p4_4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p4_5=new JPanel();	p4_5.setBackground(Color.WHITE);		add(p4_5);
		p4_5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p4_6=new JPanel();	p4_6.setBackground(Color.WHITE);		add(p4_6);
		p4_6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p5_1=new JPanel();	p5_1.setBackground(Color.black);		add(p5_1);
		p5_1.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb5_1=new JLabel("4");	p5_1.add(lb5_1);
		lb5_1.setForeground(Color.WHITE);
		lb5_1.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb5_1.setHorizontalAlignment(SwingConstants.CENTER);
		p5_2=new JPanel();	p5_2.setBackground(Color.WHITE);		add(p5_2);
		p5_2.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p5_3=new JPanel();	p5_3.setBackground(Color.WHITE);		add(p5_3);
		p5_3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p5_4=new JPanel();	p5_4.setBackground(Color.WHITE);		add(p5_4);
		p5_4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p5_5=new JPanel();	p5_5.setBackground(Color.WHITE);		add(p5_5);
		p5_5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p5_6=new JPanel();	p5_6.setBackground(Color.WHITE);		add(p5_6);
		p5_6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p6_1=new JPanel();	p6_1.setBackground(Color.black);		add(p6_1);
		p6_1.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb6_1=new JLabel("5");	p6_1.add(lb6_1);
		lb6_1.setForeground(Color.WHITE);
		lb6_1.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb6_1.setHorizontalAlignment(SwingConstants.CENTER);
		p6_2=new JPanel();p6_2.setBackground(Color.WHITE);			add(p6_2);
		p6_2.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p6_3=new JPanel();	p6_3.setBackground(Color.WHITE);		add(p6_3);
		p6_3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p6_4=new JPanel();	p6_4.setBackground(Color.WHITE);		add(p6_4);
		p6_4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p6_5=new JPanel();	p6_5.setBackground(Color.WHITE);		add(p6_5);
		p6_5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p6_6=new JPanel();	p6_6.setBackground(Color.WHITE);		add(p6_6);
		p6_6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p7_1=new JPanel();	p7_1.setBackground(Color.black);		add(p7_1);
		p7_1.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb7_1=new JLabel("6");	p7_1.add(lb7_1);
		lb7_1.setForeground(Color.WHITE);
		lb7_1.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb7_1.setHorizontalAlignment(SwingConstants.CENTER);
		p7_2=new JPanel();	p7_2.setBackground(Color.WHITE);		add(p7_2);
		p7_2.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p7_3=new JPanel();	p7_3.setBackground(Color.WHITE);		add(p7_3);
		p7_3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p7_4=new JPanel();	p7_4.setBackground(Color.WHITE);		add(p7_4);
		p7_4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p7_5=new JPanel();	p7_5.setBackground(Color.WHITE);		add(p7_5);
		p7_5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p7_6=new JPanel();	p7_6.setBackground(Color.WHITE);		add(p7_6);
		p7_6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p8_1=new JPanel();	p8_1.setBackground(Color.black);		add(p8_1);
		p8_1.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb8_1=new JLabel("7");	p8_1.add(lb8_1);
		lb8_1.setForeground(Color.WHITE);
		lb8_1.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb8_1.setHorizontalAlignment(SwingConstants.CENTER);
		p8_2=new JPanel();	p8_2.setBackground(Color.WHITE);		add(p8_2);
		p8_2.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p8_3=new JPanel();	p8_3.setBackground(Color.WHITE);		add(p8_3);
		p8_3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p8_4=new JPanel();p8_4.setBackground(Color.WHITE);			add(p8_4);
		p8_4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p8_5=new JPanel();	p8_5.setBackground(Color.WHITE);		add(p8_5);
		p8_5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p8_6=new JPanel();	p8_6.setBackground(Color.WHITE);		add(p8_6);
		p8_6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p9_1=new JPanel();	p9_1.setBackground(Color.black);		add(p9_1);
		p9_1.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		JLabel lb9_1=new JLabel("8");	p9_1.add(lb9_1);
		lb9_1.setForeground(Color.WHITE);
		lb9_1.setFont(new Font("±¼¸²", Font.BOLD, 20));
		lb9_1.setHorizontalAlignment(SwingConstants.CENTER);
		p9_2=new JPanel();	p9_2.setBackground(Color.WHITE);		add(p9_2);
		p9_2.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p9_3=new JPanel();	p9_3.setBackground(Color.WHITE);		add(p9_3);
		p9_3.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p9_4=new JPanel();	p9_4.setBackground(Color.WHITE);		add(p9_4);
		p9_4.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p9_5=new JPanel();	p9_5.setBackground(Color.WHITE);		add(p9_5);
		p9_5.setBorder(BorderFactory.createLineBorder(Color.WHITE));
		p9_6=new JPanel();	p9_6.setBackground(Color.WHITE);		add(p9_6);
		p9_6.setBorder(BorderFactory.createLineBorder(Color.WHITE));
	}

	public void fillTimeTable(Subject sj) {
		String str=sj.getStr();
		if (str.equals("¿ù123"))		{	p2_2.setBackground(Color.RED);p3_2.setBackground(Color.RED);p4_2.setBackground(Color.RED);
		}else if (str.equals("¿ù45"))	{	p5_2.setBackground(Color.LIGHT_GRAY);p6_2.setBackground(Color.LIGHT_GRAY);
		}else if (str.equals("¿ù678"))	{	p7_2.setBackground(Color.pink);p8_2.setBackground(Color.pink);p9_2.setBackground(Color.pink);
		}else if (str.equals("È­123"))	{	p2_3.setBackground(Color.orange);p3_3.setBackground(Color.orange);p4_3.setBackground(Color.orange);
		}else if (str.equals("È­45"))	{	p5_3.setBackground(Color.LIGHT_GRAY);p6_3.setBackground(Color.LIGHT_GRAY);
		}else if (str.equals("È­678")) 	{	p7_3.setBackground(Color.magenta);p8_3.setBackground(Color.magenta);p9_3.setBackground(Color.magenta);
		}else if (str.equals("¼ö123"))	{	p2_4.setBackground(Color.YELLOW);p3_4.setBackground(Color.YELLOW);p4_4.setBackground(Color.YELLOW);
		}else if (str.equals("¼ö45"))	{	p5_4.setBackground(Color.LIGHT_GRAY);p6_4.setBackground(Color.LIGHT_GRAY);
		}else if (str.equals("¼ö678")) 	{	p7_4.setBackground(Color.CYAN);p8_4.setBackground(Color.CYAN);p9_4.setBackground(Color.CYAN);
		}else if (str.equals("¸ñ123")) 	{	p2_5.setBackground(Color.green);p3_5.setBackground(Color.green);p4_5.setBackground(Color.green);
		}else if (str.equals("¸ñ45")) 	{	p5_5.setBackground(Color.LIGHT_GRAY);p6_5.setBackground(Color.LIGHT_GRAY);
		}else if (str.equals("¸ñ678")) 	{	p7_5.setBackground(Color.GRAY);p8_5.setBackground(Color.GRAY);p9_5.setBackground(Color.GRAY);
		}else if (str.equals("±Ý123"))	{	p2_6.setBackground(Color.BLUE);p3_6.setBackground(Color.BLUE);p4_6.setBackground(Color.BLUE);
		}else if (str.equals("±Ý45"))	{	p5_6.setBackground(Color.LIGHT_GRAY);p6_6.setBackground(Color.LIGHT_GRAY);
		}else if (str.equals("±Ý678"))	{	p7_6.setBackground(Color.darkGray);p8_6.setBackground(Color.darkGray);p9_6.setBackground(Color.darkGray);
		}
	}

	public void reTimeTable(Subject sj) {
		String str=sj.getStr();
		if (str.equals("¿ù123"))		{	p2_2.setBackground(Color.WHITE);p3_2.setBackground(Color.WHITE);p4_2.setBackground(Color.WHITE);
		}else if (str.equals("¿ù45"))	{	p5_2.setBackground(Color.WHITE);p6_2.setBackground(Color.WHITE);
		}else if (str.equals("¿ù678"))	{	p7_2.setBackground(Color.WHITE);p8_2.setBackground(Color.WHITE);p9_2.setBackground(Color.WHITE);
		}else if (str.equals("È­123"))	{	p2_3.setBackground(Color.WHITE);p3_3.setBackground(Color.WHITE);p4_3.setBackground(Color.WHITE);
		}else if (str.equals("È­45"))	{	p5_3.setBackground(Color.WHITE);p6_3.setBackground(Color.WHITE);
		}else if (str.equals("È­678")) 	{	p7_3.setBackground(Color.WHITE);p8_3.setBackground(Color.WHITE);p9_3.setBackground(Color.WHITE);
		}else if (str.equals("¼ö123"))	{	p2_4.setBackground(Color.WHITE);p3_4.setBackground(Color.WHITE);p4_4.setBackground(Color.WHITE);
		}else if (str.equals("¼ö45"))	{	p5_4.setBackground(Color.WHITE);p6_4.setBackground(Color.WHITE);
		}else if (str.equals("¼ö678")) 	{	p7_4.setBackground(Color.WHITE);p8_4.setBackground(Color.WHITE);p9_4.setBackground(Color.WHITE);
		}else if (str.equals("¸ñ123")) 	{	p2_5.setBackground(Color.WHITE);p3_5.setBackground(Color.WHITE);p4_5.setBackground(Color.WHITE);
		}else if (str.equals("¸ñ45")) 	{	p5_5.setBackground(Color.WHITE);p6_5.setBackground(Color.WHITE);
		}else if (str.equals("¸ñ678")) 	{	p7_5.setBackground(Color.WHITE);p8_5.setBackground(Color.WHITE);p9_5.setBackground(Color.WHITE);
		}else if (str.equals("±Ý123"))	{	p2_6.setBackground(Color.WHITE);p3_6.setBackground(Color.WHITE);p4_6.setBackground(Color.WHITE);
		}else if (str.equals("±Ý45"))	{	p5_6.setBackground(Color.WHITE);p6_6.setBackground(Color.WHITE);
		}else if (str.equals("±Ý678"))	{	p7_6.setBackground(Color.WHITE);p8_6.setBackground(Color.WHITE);p9_6.setBackground(Color.WHITE);
		}
	}
	
}
